config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  # Utility
  get "/up", to: proc { [ 200, {}, [ "OK" ] ] }

  # Landing page
  get "home/index"
  post "/notify_me", to: "home#notify_me", as: "notify_me"
  get "/notify_me/success", to: "home#notify_me_success", as: "notify_me_success"

  # Public-facing routes
  get "/audition/:hex_code", to: "respond_to_call_to_audition#new", as: "respond_to_call_to_audition"
  post "/audition/:hex_code", to: "respond_to_call_to_audition#create", as: "handle_respond_to_call_to_audition"
  get "/audition/:hex_code/success", to: "respond_to_call_to_audition#success", as: "respond_to_call_to_audition_success"
  get "/audition/:hex_code/inactive", to: "respond_to_call_to_audition#inactive", as: "respond_to_call_to_audition_inactive"

  resource :session
  resources :passwords, param: :token

  scope "/app" do
    get "/", to: "dashboard#index", as: "dashboard"

    resources :production_companies
    resources :people do
      collection do
        get :search
      end
    end

    resources :productions do
      resources :shows

      resources :casts do
        member do
          post :add_person
          post :remove_person
        end
      end

      resources :roles

      resources :call_to_auditions do
        resources :questions
        resources :audition_requests
        # Set status on audition requests
        post "audition_requests/:id/set_status/:status", to: "audition_requests#set_status", as: "audition_request_set_status"
      end
      get "call_to_auditions/:id/preview", to: "call_to_auditions#preview", as: "call_to_audition_preview"

      get "/audition_sessions/summary", to: "audition_sessions#summary", as: "audition_session_summary"
      resources :audition_sessions do
        get "/auditions/:id", to: "audition_sessions#show", as: "audition"
      end

      resources :auditions
    end

    # Used for adding people and removing them from an audition session
    post "/auditions/add_to_session", to: "auditions#add_to_session"
    post "/auditions/remove_from_session", to: "auditions#remove_from_session"

    # Used for adding people and removing them from a cast
    post "/shows/:id/assign_person_to_role", to: "shows#assign_person_to_role"
  end

  # Junkers
  get "wp-includes/id3/licence.txt", to: proc { [ 200, {}, [ "" ] ] }
end

app/models/audition.rb
class Audition < ApplicationRecord
  belongs_to :person
  belongs_to :audition_request

  has_and_belongs_to_many :audition_sessions
end

app/controllers/auditions_controller.rb
class AuditionsController < ApplicationController
  before_action :set_production, except: %i[ add_to_session remove_from_session ]
  before_action :set_audition, only: %i[ show edit update destroy ]

  # GET /auditions
  def index
    @auditions = Audition.all
  end

  # GET /auditions/1
  def show
  end

  # GET /auditions/new
  def new
    @audition = Audition.new
  end

  # GET /auditions/1/edit
  def edit
  end

  # POST /auditions
  def create
    @audition = Audition.new(audition_params)

    if @audition.save
      redirect_to @audition, notice: "Audition was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /auditions/1
  def update
    if @audition.update(audition_params)
      redirect_to @audition, notice: "Audition was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /auditions/1
  def destroy
    @audition.destroy!
    redirect_to auditions_path, notice: "Audition was successfully destroyed.", status: :see_other
  end



  # POST /auditions/add_to_session
  def add_to_session
    audition_request = AuditionRequest.find(params[:audition_request_id])
    audition_session = AuditionSession.find(params[:audition_session_id])

    audition = Audition.create!(audition_request: audition_request, person: audition_request.person)
    audition_session.auditions << audition unless audition_session.auditions.include?(audition)

    # Re-render the left list and the dropzone partials
    left_list_html = render_to_string(partial: "audition_sessions/left_list", locals: { production: audition_session.production, filter: cookies[:audition_request_filter] })
    dropzone_html = render_to_string(partial: "audition_sessions/dropzone", locals: { audition_session: audition_session })

    render json: { left_list_html: left_list_html, dropzone_html: dropzone_html }
  end

  def remove_from_session
    audition = Audition.find(params[:audition_id])
    audition_session = AuditionSession.find(params[:audition_session_id])
    audition_session.auditions.delete(audition)

    left_list_html = render_to_string(partial: "audition_sessions/left_list", locals: { production: audition_session.production, filter: cookies[:audition_request_filter] })
    dropzone_html = render_to_string(partial: "audition_sessions/dropzone", locals: { audition_session: audition_session })

    render json: { left_list_html: left_list_html, dropzone_html: dropzone_html }
  end


  private
   def set_production
      @production = Production.find(params.expect(:production_id))
    end

    def set_audition
      @audition = @production.auditions.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def audition_params
      params.expect(audition: [ :audition_session_id, :audition_request_id ])
    end
end

app/views/auditions/_form.html.erb
<%= form_with(model: audition, class: "contents") do |form| %>
  <% if audition.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(audition.errors.count, "error") %> prohibited this audition from being saved:</h2>

      <ul class="list-disc ml-6">
        <% audition.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :audition_session %>
    <%= form.collection_select :audition_session_id, AuditionSession.all, :id, :display_name, prompt: "Select an Audition Session" %>
  </div>

  <div class="my-5">
    <%= form.label :audition_request %>
    <%= form.collection_select :audition_request_id, AuditionRequest.all, :id, :display_name, prompt: "Select an Audition Request" %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-lg px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/auditions/edit.html.erb
<% content_for :title, "Editing audition" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing audition</h1>

  <%= render "form", audition: @audition %>

  <%= link_to "Show this audition", @audition, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-lg px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to auditions", auditions_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-lg px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/auditions/index.html.erb
<% content_for :title, "Auditions" %>

<div class="w-full mb-10">
  <%= render partial: "shared/notice", locals: { notice: notice } %>
  <%= render partial: "shared/top_menu", locals: {
    breadcrumbs: [],
    text: "Auditions",
    links: []
  } %>

  <div class="w-full mt-10">
    <h1 class="font-bold text-2xl">Call to Audition</h1>
    <% if !@production.call_to_auditions.any? %>
      <div class="mb-5">
        You don&apos;t currently have any open Calls to Audition for this production.
      </div>
      <%= render partial: "shared/link_button", locals: {text: "Open a Call to Audition", path: new_production_call_to_audition_path(@production)} %>
    <% end %>
  </div>
  <div class="w-full">
    <% @production.call_to_auditions.order(:opens_at).each do |call_to_audition| %>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-1 md:gap-4">

        <div class="p-4 pb-6 border border-gray-200 rounded-lg hover:border-gray-400 transition-all">
          <p class="mb-2">

            <% if call_to_audition.timeline_status == :upcoming %>
              You've scheduled your Call to Audition to open
              on <b><%= call_to_audition.opens_at.strftime("%B %-d, %Y") %></b> and
              close on <b><%= call_to_audition.closes_at.strftime("%B %-d, %Y") %></b>.
            <% elsif call_to_audition.timeline_status == :open %>
              Your Call to Audition has been open since
              <b><%= call_to_audition.opens_at.strftime("%B %-d, %Y") %></b> and
              will close on <b><%= call_to_audition.closes_at.strftime("%B %-d, %Y") %></b>.
            <% else %>
              Your Call to Audition began
              on <b><%= call_to_audition.opens_at.strftime("%B %-d, %Y") %></b> and
              closed on <b><%= call_to_audition.closes_at.strftime("%B %-d, %Y") %></b>.
            <% end %>

          </p>

          <h2 class="font-bold text-lg col-span-1 mb-2 border-t-2 border-gray-200 pt-3 mt-5">Sign-up Form</h2>
          <div>
            <div class="w-full flex items-center mx-auto" data-controller="clipboard">
              <%= text_field_tag "", call_to_audition.respond_url, class: "block w-64 text-sm text-black bg-white shadow-sm rounded-lg border px-3 py-2 w-full border-gray-400", disabled: true, data: { clipboard_target: "textField" } %>
              <p class="ml-1 font-medium rounded-lg text-sm px-2 py-1 h-9 text-center mb-0 inline-block bg-pink-500 text-white hover:bg-gray-100 hover:text-pink-500 focus:ring-4 focus:outline-none focus:ring-gray-200 cursor-pointer" data-action="click->clipboard#copy">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 0 0 2.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 0 0-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 0 0 .75-.75 2.25 2.25 0 0 0-.1-.664m-5.8 0A2.251 2.251 0 0 1 13.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25ZM6.75 12h.008v.008H6.75V12Zm0 3h.008v.008H6.75V15Zm0 3h.008v.008H6.75V18Z" />
                </svg>
              </p>
            </div>
            <div class="mt-2">
              <%= render partial: "shared/link_button", locals: {text: "Edit Form", path: edit_production_call_to_audition_path(@production, call_to_audition)} %>
              <%= render partial: "shared/link_button", locals: {text: "Preview Form", path: production_call_to_audition_preview_path(@production, call_to_audition)} %>
            </div>
          </div>

        </div>

        <div class="p-4 pb-6 border border-gray-200 rounded-lg hover:border-gray-400 transition-all">
          <h2 class="font-bold text-lg col-span-1 mb-2">Audition Requests</h2>
          <div class="grid grid-cols-2 gap-2 mb-4">
            <%= link_to production_call_to_audition_audition_requests_path(@production, call_to_audition, status: :unreviewed) do %>
              <div class="p-4 border border-gray-200 rounded-lg hover:border-gray-400 transition-all min-h-24">
                <p class="font-bold text-5xl text-center"><%= call_to_audition.counts[:unreviewed] %></p>
                <p class="text-xs text-center">Unreviewed</p>
              </div>
            <% end %>
            <%= link_to production_call_to_audition_audition_requests_path(@production, call_to_audition, status: :undecided) do %>
              <div class="p-4 border border-gray-200 rounded-lg hover:border-gray-400 transition-all min-h-24">
                <p class="font-bold text-5xl text-center"><%= call_to_audition.counts[:undecided] %></p>
                <p class="text-xs text-center">Undecided</p>
              </div>
            <% end %>
            <%= link_to production_call_to_audition_audition_requests_path(@production, call_to_audition, status: :accepted) do %>
              <div class="p-4 border border-gray-200 rounded-lg hover:border-gray-400 transition-all min-h-24">
                <p class="font-bold text-5xl text-center"><%= call_to_audition.counts[:accepted] %></p>
                <p class="text-xs text-center">Accepted</p>
              </div>
            <% end %>
            <%= link_to production_call_to_audition_audition_requests_path(@production, call_to_audition, status: :passed) do %>
              <div class="p-4 border border-gray-200 rounded-lg hover:border-gray-400 transition-all min-h-24">
                <p class="font-bold text-5xl text-center"><%= call_to_audition.counts[:passed] %></p>
                <p class="text-xs text-center">Passed</p>
              </div>
            <% end %>
          </div>
          <%= render partial: "shared/link_button", locals: {text: "View all Audition Requests", path: production_call_to_audition_audition_requests_path(@production, call_to_audition)} %>
        </div>

      </div>
    </div>
    <div class="w-full mt-10">
      <h1 class="font-bold text-2xl mb-2">Auditions</h1>
      <div class="grid grid-cols-1">
        <div class="p-4 border border-gray-200 rounded-lg hover:border-gray-400 transition-all">

          <% if @production.audition_sessions.any? %>
            <div class="grid grid-cols-1 gap-1 mb-2">
              <% @production.audition_sessions.each do |session| %>
                <%= link_to production_audition_session_path(@production, session) do %>
                  <div class="p-3 border border-gray-200 rounded-lg hover:border-gray-400 transition-all">
                    <div class="flex flex-row items-center justify-between mb-2">
                      <p class="text-md font-semibold"><%= session.start_at.strftime("%-m/%-d/%Y at %-l:%M %p") %></p>
                    </div>
                    <% if session.auditions.any? %>
                      <div class="grid grid-cols-8 lg:grid-cols-12 gap-1 w-full">
                        <% session.auditions.each do |audition| %>
                          <div class="flex flex-col items-center p-3 border border-gray-200 rounded-lg hover:border-gray-400 transition-all">
                            <%= image_tag audition.person.headshot.variant(:thumb), alt: audition.person.stage_name, class: "w-10 h-10 rounded-lg object-cover mb-1" if audition.person.headshot.present? %>
                            <span class="font-medium text-xs text-center"><%= audition.person.stage_name.truncate(20, omission: '...') %></span>
                          </div>
                        <% end %>

                        <% if (!session.is_full? && !session.is_overbooked?) %>
                          <span class="inline-flex items-center text-xs text-gray-400 h-full text-center ml-2">
                              <div class="flex flex-col items-center justify-center">
                                  Add up to<br><%= session.maximum_auditionees - session.auditions.count %> more
                              </div>
                          </span>
                        <% end %>

                      </div>
                    <% else %>
                      <p class="text-gray-400 font-semibold text-xs">No auditions scheduled for this session.</p>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
            </div>
          <% end %>

          <div class="flex justify-between space-x-2">
            <div>
              <% if @production.audition_sessions.any? %>
                <%= render partial: "shared/link_button", locals: {text: "Manage Audition Sessions", path: production_audition_sessions_path(@production)} %>
              <% end %>

              <%= render partial: "shared/link_button", locals: {text: "+ Schedule an Audition Session", path: new_production_audition_session_path(@production)} %>
            </div>
            <div>
              <%= render partial: "shared/link_button", locals: {text: "Audition Session Summary", path: production_audition_session_summary_path(@production)} %>
            </div>
          </div>

        </div>

      </div>
    <% end %>
  </div>
</div>

app/views/auditions/new.html.erb
<% content_for :title, "New audition" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New audition</h1>

  <%= render "form", audition: @audition %>

  <%= link_to "Back to auditions", auditions_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-lg px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/auditions/show.html.erb
<% content_for :title, "Showing audition" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing audition</h1>

  <%= render @audition %>

  <%= link_to "Edit this audition", edit_audition_path(@audition), class: "w-full sm:w-auto text-center rounded-lg px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to auditions", auditions_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-lg px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this audition", @audition, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-lg px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>