config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  # Utility
  get "/up", to: proc { [ 200, {}, [ "OK" ] ] }

  # Landing page
  get "home/index"
  post "/notify_me", to: "home#notify_me", as: "notify_me"
  get "/notify_me/success", to: "home#notify_me_success", as: "notify_me_success"

  # Public-facing routes
  get "/audition/:hex_code", to: "respond_to_call_to_audition#new", as: "respond_to_call_to_audition"
  post "/audition/:hex_code", to: "respond_to_call_to_audition#create", as: "handle_respond_to_call_to_audition"
  get "/audition/:hex_code/success", to: "respond_to_call_to_audition#success", as: "respond_to_call_to_audition_success"
  get "/audition/:hex_code/inactive", to: "respond_to_call_to_audition#inactive", as: "respond_to_call_to_audition_inactive"

  resource :session
  resources :passwords, param: :token

  scope "/app" do
    get "/", to: "dashboard#index", as: "dashboard"

    resources :production_companies
    resources :people do
      collection do
        get :search
      end
    end

    resources :productions do
      resources :shows

      resources :casts do
        member do
          post :add_person
          post :remove_person
        end
      end

      resources :roles

      resources :call_to_auditions do
        resources :questions
        resources :audition_requests
        # Set status on audition requests
        post "audition_requests/:id/set_status/:status", to: "audition_requests#set_status", as: "audition_request_set_status"
      end
      get "call_to_auditions/:id/preview", to: "call_to_auditions#preview", as: "call_to_audition_preview"

      get "/audition_sessions/summary", to: "audition_sessions#summary", as: "audition_session_summary"
      resources :audition_sessions do
        get "/auditions/:id", to: "audition_sessions#show", as: "audition"
      end

      resources :auditions
    end

    # Used for adding people and removing them from an audition session
    post "/auditions/add_to_session", to: "auditions#add_to_session"
    post "/auditions/remove_from_session", to: "auditions#remove_from_session"

    # Used for adding people and removing them from a cast
    post "/shows/:id/assign_person_to_role", to: "shows#assign_person_to_role"
  end

  # Junkers
  get "wp-includes/id3/licence.txt", to: proc { [ 200, {}, [ "" ] ] }
end

app/models/call_to_audition.rb
class CallToAudition < ApplicationRecord
  belongs_to :production
  has_many :audition_requests, dependent: :destroy
  has_many :audition_sessions, dependent: :destroy
  has_many :questions, as: :questionable, dependent: :destroy

  has_rich_text :header_text
  has_rich_text :success_text

  validates :opens_at, presence: true
  validates :closes_at, presence: true

  def production_name
    self.production.name
  end

  def counts
    {
      unreviewed: self.audition_requests.where(status: :unreviewed).count,
      undecided: self.audition_requests.where(status: :undecided).count,
      passed: self.audition_requests.where(status: :passed).count,
      accepted: self.audition_requests.where(status: :accepted).count
    }
  end

  def timeline_status
    if self.opens_at > Time.current
      :upcoming
    elsif self.closes_at <= Time.current
      :closed
    else
      :open
    end
  end

  def respond_url
    if Rails.env.development?
      "http://localhost:3000" + Rails.application.routes.url_helpers.respond_to_call_to_audition_path(self.hex_code)
    else
      "https://www.cocoscout.com" + Rails.application.routes.url_helpers.respond_to_call_to_audition_path(self.hex_code)
    end
  end
end

app/controllers/call_to_auditions_controller.rb
class CallToAuditionsController < ApplicationController
  before_action :set_production
  before_action :set_call_to_audition, only: %i[ edit update destroy preview ]

  # Use the public facing layout on the preview
  layout "public_facing", only: [ :preview ]


  # GET /call_to_auditions/new
  def new
    @call_to_audition = CallToAudition.new
  end

  # GET /call_to_auditions/1/edit
  def edit
  end

  # POST /call_to_auditions
  def create
    @call_to_audition = CallToAudition.new(call_to_audition_params)
    @call_to_audition.production = @production

    # Create a random hex code for the audition link
    @call_to_audition.hex_code = SecureRandom.alphanumeric(5).upcase

    # Make sure it's unique and regenerate if not
    while CallToAudition.exists?(hex_code: @call_to_audition.hex_code)
      @call_to_audition.hex_code = SecureRandom.alphanumeric(5).upcase
    end

    if @call_to_audition.save
      redirect_to edit_production_call_to_audition_path(@production, @call_to_audition), notice: "Call to Audition was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /call_to_auditions/1
  def update
    if @call_to_audition.update(call_to_audition_params)
      redirect_to production_auditions_path(@production), notice: "Call to Audition was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /call_to_auditions/1
  def destroy
    @call_to_audition.destroy!
    redirect_to @production, notice: "Call to Audition was successfully deleted.", status: :see_other
  end

  def preview
    @audition_request = AuditionRequest.new
    @person = @audition_request.build_person
    @questions = @call_to_audition.questions.order(:created_at) # TODO Change this to be re-arrangeable
    @answers = {}
  end

  private
   def set_production
      @production = Production.find(params.expect(:production_id))
    end

    def set_call_to_audition
      @call_to_audition = CallToAudition.find(params.expect(:id))
    end

    def call_to_audition_params
      params.expect(call_to_audition: [ :production_id, :opens_at, :closes_at, :header_text, :success_text, :hex_code ])
    end
end

app/views/call_to_auditions/edit.html.erb
<% content_for :title, "Editing call to audition" %>
<div class="w-full">
  <%= render partial: "shared/notice", locals: { notice: notice } %>
  <%= render partial: "shared/top_menu", locals: {
    breadcrumbs: [
      ["Auditions", production_auditions_path(@production)]
    ],
    text: "Call to Audition",
    links: []
  } %>
  <%= form_with(model: [@production, @call_to_audition], class: "contents") do |form| %>
    <% if @call_to_audition.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(@call_to_audition.errors.count, "error") %> prohibited this call_to_audition from being saved:</h2>
        <ul class="list-disc ml-6">
          <% call_to_audition.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="w-full">
      <h1 class="font-bold text-2xl">Dates</h1>
      <p class="text-sm text-gray-500">When should this Call to Audition open and close? While it&apos;s open, members of the public will be able to request an audition.</p>
    </div>
    <div class="flex border-b-1 border-gray-200 mb-5">
      <div class="my-5 w-1/2 mr-5">
        <%= form.label :opens_at, "Open At:" %>
        <%= form.datetime_field :opens_at, class: ["block shadow-sm rounded-lg border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": @call_to_audition.errors[:opens_at].none?, "border-red-400 focus:outline-red-600": @call_to_audition.errors[:opens_at].any?}] %>
      </div>
      <div class="my-5 w-1/2 ml-5">
        <%= form.label :closes_at, "Close At:" %>
        <%= form.datetime_field :closes_at, class: ["block shadow-sm rounded-lg border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": @call_to_audition.errors[:closes_at].none?, "border-red-400 focus:outline-red-600": @call_to_audition.errors[:closes_at].any?}] %>
      </div>
    </div>
    <div class="w-full">
      <h1 class="font-bold text-2xl">Sign-up Form</h1>
      <p class="text-sm text-gray-500">You can customize the sign-up form to personalize it to your production.</p>
    </div>
    <div class="my-5">
      <%= form.label :header_text, "Header Text:" %>
      <%= form.rich_text_area :header_text, class: ["block shadow-sm rounded-lg border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": @call_to_audition.errors[:header_text].none?, "border-red-400 focus:outline-red-600": @call_to_audition.errors[:header_text].any?}] %>
    </div>
    <div class="my-5">
      <%= form.label :header_text, "Success Text:" %>
      <%= form.rich_text_area :success_text, class: ["block shadow-sm rounded-lg border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": @call_to_audition.errors[:success_text].none?, "border-red-400 focus:outline-red-600": @call_to_audition.errors[:success_text].any?}] %>
    </div>
    <div class="w-full border-t-1 border-gray-200 pt-5">
      <h1 class="font-bold text-2xl">Custom Questions</h1>
      <p class="text-sm text-gray-500">You can add additional questions to your sign-up form.</p>
    </div>
    <div class="w-full ">
      <%= render partial: "shared/link_button", locals: {text: "Manage Custom Questions", path: production_call_to_audition_questions_path(@production, @call_to_audition)} %>
    </div>
    <div class="w-full border-t border-gray-200 pt-5 my-5">
      <%= form.submit "Update", class: "w-full sm:w-auto rounded-lg px-3.5 py-2.5 bg-gradient-to-r from-pink-400 via-pink-500 to-pink-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-pink-300 dark:focus:ring-pink-800 text-white inline-block font-medium cursor-pointer" %>
      <%= link_to "Back", production_path(@production), class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-lg px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
    </div>
  <% end %>

</div>

app/views/call_to_auditions/new.html.erb
<% content_for :title, "New call to audition" %>
<div class="w-full">
  <%= render partial: "shared/notice", locals: { notice: notice } %>
  <%= render partial: "shared/top_menu", locals: {
    breadcrumbs: [
      ["Productions", productions_path],
      [@production.name, production_path(@production)]
    ],
    text: "Open a Call to Audition",
    links: []
  } %>
  <%= form_with(model: [@production, @call_to_audition], class: "contents") do |form| %>
    <% if @call_to_audition.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(@call_to_audition.errors.count, "error") %> prohibited this call_to_audition from being saved:</h2>
        <ul class="list-disc ml-6">
          <% @call_to_audition.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="w-full">
      <h1 class="font-bold text-2xl">Dates</h1>
      <p class="text-sm text-gray-500">When should this Call to Audition open and close? While it&apos;s open, members of the public will be able to request an audition.</p>
    </div>
    <div class="flex border-b-1 border-gray-200 mb-5">
      <div class="my-5 w-1/2 mr-5">
        <%= form.label :opens_at, "Open At:" %>
        <%= form.datetime_field :opens_at, class: ["block shadow-sm rounded-lg border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": @call_to_audition.errors[:opens_at].none?, "border-red-400 focus:outline-red-600": @call_to_audition.errors[:opens_at].any?}] %>
      </div>
      <div class="my-5 w-1/2 ml-5">
        <%= form.label :closes_at, "Close At:" %>
        <%= form.datetime_field :closes_at, class: ["block shadow-sm rounded-lg border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": @call_to_audition.errors[:closes_at].none?, "border-red-400 focus:outline-red-600": @call_to_audition.errors[:closes_at].any?}] %>
      </div>
    </div>
    <div class="inline">
      <%= form.submit "Open", class: "w-full sm:w-auto rounded-lg px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>
  <%= link_to "Back", production_path(@production), class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-lg px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/call_to_auditions/preview.html.erb
<div class="fixed top-0 left-0 h-16 w-full bg-pink-500 text-pink-500 p-3">
  <div class="flex justify-between items-center h-full mx-auto content-center">
    <%= render partial: "shared/link_button", locals: {text: "Close Preview", color: "white", path: production_path(@production)} %>
    <p class="text-white text-2xl font-medium">Preview</p>
    <%= render partial: "shared/link_button", locals: {text: "Edit", color: "white", path: edit_production_call_to_audition_path(@production, @call_to_audition)} %>
  </div>
</div>


<div class="fixed bottom-0 left-0 h-16 w-full bg-pink-500 text-pink-500 p-3">
  <div class="w-full md:w-1/2 flex items-center mx-auto" data-controller="clipboard">
    <p class="text-nowrap text-white text-sm mr-2">Shareable Link:</p>
    <%= text_field_tag "", @call_to_audition.respond_url, class: "block w-64 text-sm text-black bg-white shadow-sm rounded-lg border px-3 py-2 w-full border-gray-400", disabled: true, data: { clipboard_target: "textField" }  %>
    <p class="ml-1 font-medium rounded-lg text-sm px-2 py-1 h-9 text-center mb-0 inline-block text-pink-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 cursor-pointer" data-action="click->clipboard#copy">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 0 0 2.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 0 0-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 0 0 .75-.75 2.25 2.25 0 0 0-.1-.664m-5.8 0A2.251 2.251 0 0 1 13.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25ZM6.75 12h.008v.008H6.75V12Zm0 3h.008v.008H6.75V15Zm0 3h.008v.008H6.75V18Z" />
      </svg>
    </p>
  </div>
</div>

<div class="w-full max-w-4xl mt-12 mb-18">
  <h1 class="font-bold text-4xl"><%= @production.name %></h1>
  <h2 class="font-bold text-2xl pt-5">Apply for an audition</h2>

  <% if @call_to_audition.header_text.present? %>
    <div class="pt-5">
      <%= @call_to_audition.header_text %>
    </div>
  <% end %>

  <%= form_with(model: @audition_request, url: "", method: :get, class: "contents", data: { turbo: false }) do |form| %>

    <% if @audition_request.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(@audition_request.errors.count, "error") %> prohibited this audition_request from being saved:</h2>

        <ul class="list-disc ml-6">
          <% @audition_request.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.fields_for @person do |person_form| %>
      <%= render partial: "shared/person_form", locals: { person_form: person_form } %>
    <% end %>

    <% if @questions.any? %>
      <% @questions.each do |question| %>
        <div class="my-5">
          <label><%= question.text %></label>

          <% if question.question_type == "text" %>

            <%= text_area_tag "question[#{question.id}]", @answers[question.id], class: ["block shadow-sm rounded-lg border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": @person.errors[:socials].none?, "border-red-400 focus:outline-red-600": @person.errors[:socials].any?}] %>

          <% elsif question.question_type == "yesno" %>

            <div class="px-2 py-1">
              <%= radio_button_tag "question[#{question.id}]", "yes", checked: (@answers[question.id] == "yes" || @answers[question.id].blank?), class: "accent-pink-500 mr-1" %>
              <%= label_tag "question[#{question.id}][yes]", "Yes" %>
            </div>
            <div class="px-2 py-1">
              <%= radio_button_tag "question[#{question.id}]", "no", checked: (@answers[question.id] == "no"), class: "accent-pink-500 mr-1" %>
              <%= label_tag "question[#{question.id}][no]", "No" %>
            </div>

          <% elsif question.question_type == "multiple-multiple" %>

            <label class="text-sm text-gray-500">(Select all that apply)</label>

            <% question.question_options.each do |option| %>
              <div class="px-2 py-1">
                <%= check_box_tag "question[#{question.id}][#{option.text}]", option.text, @answers[question.id]&.include?(option.text),class: "accent-pink-500 mr-1" %>
                <%= label_tag "question[#{question.id}][#{option.text}]", option.text %>
              </div>
            <% end %>

          <% elsif question.question_type == "multiple-single" %>

            <label class="text-sm text-gray-500">(Select one)</label>

            <% question.question_options.each do |option| %>
              <div class="px-2 py-1">
                <%= radio_button_tag "question[#{question.id}]", option.text, @answers[question.id] == option.text, class: "accent-pink-500 mr-1" %>
                <%= label_tag "question[#{question.id}][#{option.text}]", option.text %>
              </div>
            <% end %>

        <% end %>

        </div>
      <% end %>
    <% end %>

    <div class="inline pb-5">
      <%= form.submit "Submit", class: "w-full sm:w-auto rounded-lg px-3.5 py-2.5 text-white bg-gradient-to-r from-pink-400 via-pink-500 to-pink-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-pink-300 dark:focus:ring-pink-800 inline-block font-medium cursor-pointer" %>
    </div>

  <% end %>

</div>